# Generated by Django 4.1.4 on 2022-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('data_create', models.DateField(verbose_name='Дата изготовления')),
                ('expire_date', models.DateField(verbose_name='Срок годности')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания поста')),
                ('made_in', models.CharField(max_length=100, verbose_name='Место изготовления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title', 'create_at'],
            },
        ),
    ]
