# Generated by Django 4.1.4 on 2022-12-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Характеристика')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('expire_date', models.DateField(verbose_name='Срок годности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('made_in', models.CharField(max_length=255, verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['created_at'],
            },
        ),
    ]
