# Generated by Django 4.1.4 on 2022-12-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title', 'create_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
