# Generated by Django 4.1.4 on 2022-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_options_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-create_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='products',
            name='data_create',
            field=models.DateTimeField(verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='products',
            name='expire_date',
            field=models.DateTimeField(verbose_name='Срок годности'),
        ),
    ]
